# Generated by Django 5.0.2 on 2024-04-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JKMapp', '0002_personaldetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
